config/routes.rb
Rails.application.routes.draw do

  resources :books do
    resource :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  devise_for :users
    resources :users,only: [:show,:index,:edit,:update] do
      get "search", to: "users#search"
      resource :relationships, only: [:create, :destroy]
      member do
        get :following, :followers
      end
    end


  resources :groups do
    member do
      get :join
    end
    get "new/mail" => "groups#new_mail"
    get "send_mail" => "groups#send_mail"
  end

  root 'homes#top'
  get 'home/about' => 'homes#about'

  get '/search', to: 'searchs#search'



end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = @book.id
    @book_comment.save
  end

  def destroy
    @book_comment = BookComment.find(params[:book_id]).destroy
    @book = @book_comment.book
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_count.html.erb
コメント数: <%= book.book_comments.count %>

app/views/book_comments/_form.html.erb
<table class='table'>
  <%= form_with(model:[book,book_comment],method: :post, remote: true) do |f| %>
    <%= f.text_area :comment, rows:'5',class:"form-control" %>
    <%= f.submit "送信" %>
  <% end %>
</table>

app/views/book_comments/_index.html.erb
<% book.book_comments.each do |book_comment| %>
  <tr>
    <td>
      <%= link_to user_path(book_comment.user) do %>
        <%= attachment_image_tag(book_comment.user, :profile_image, fallback: "no-image-icon.jpg", size:'40x40') %><br>
        <%= book_comment.user.name %>
      <% end %>
    </td>
    <td><%= book_comment.comment %></td>
    <td>
      <% if book_comment.user_id == current_user.id %>
        <%= link_to "Destroy", book_book_comments_path(book_comment.id), method: :delete, remote: true, class:"btn btn-sm btn-danger destroy_book_#{book_comment.id}" %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/book_comments/create.js.erb
$("#comments-count").html("コメント数: <%= @book.book_comments.count %>");
$("#comments-area").html("<%= j(render 'book_comments/index', book: @book) %>");
$("#book_comment_comment").val('');

app/views/book_comments/destroy.js.erb
$("#comments-count").html("コメント数: <%= @book.book_comments.count %>");
$("#comments-area").html("<%= j(render 'book_comments/index', book: @book) %>");
$("#book_comment_comment").val('');