config/routes.rb
Rails.application.routes.draw do

  resources :books do
    resource :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  devise_for :users
    resources :users,only: [:show,:index,:edit,:update] do
      get "search", to: "users#search"
      resource :relationships, only: [:create, :destroy]
      member do
        get :following, :followers
      end
    end


  resources :groups do
    member do
      get :join
    end
    get "new/mail" => "groups#new_mail"
    get "send_mail" => "groups#send_mail"
  end

  root 'homes#top'
  get 'home/about' => 'homes#about'

  get '/search', to: 'searchs#search'



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_books, through: :favorites, source: :book
  has_many :book_comments, dependent: :destroy

  attachment :profile_image, destroy: false

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :owned_groups, class_name: "Group"

  #foregin_key = 入り口。source = 出口

  has_many :relationships
  #active_relationshipsという架空のクラス（モデル）を作成、relationshipsのfollower_idを参考にactiverelationshipsにアクセスする
  has_many :active_relationships, class_name:  "Relationship",foreign_key: "follower_id",dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",foreign_key: "followed_id",dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

def follow(user_id)
  self.active_relationships.create!(followed_id: user_id)
end

#フォローがあればアンフォローする
def unfollow(user_id)
  self.active_relationships.find_by(followed_id: user_id).destroy
end

def following?(user)
  self.following.include?(user)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @today_book = @books.today
    @yesterday_book = @books.yesterday
    @two_day_book = @books.two_day_ago
    @three_day_book = @books.three_day_ago
    @four_day_book = @books.four_day_ago
    @five_day_book = @books.five_day_ago
    @six_day_book = @books.six_day_ago
    @data = [['６日前', @books.six_day_ago.count],['５日前', @books.five_day_ago.count],['４日前', @books.four_day_ago.count], ['３日前', @books.three_day_ago.count], ['２日前', @books.two_day_ago.count], ['1日前', @books.yesterday.count], ['今日', @books.today.count]]
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def following
    @users = User.find(params[:id])
    @user = @users.following
    render 'relationships/following'
  end

  def followers
    @users = User.find(params[:id])
    @user = @users.followers
    render 'relationships/followers'
  end

  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    if params[:created_at] == ""
      @search_book = "日付を選択してください"
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, fallback: "no-image-icon.jpg", size:'40x40') %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.following.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td>
          <% unless current_user == user %>
            <%= render "relationships/follow", user: user %>
          <% end %>

        </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>

  <%= attachment_image_tag(user, :profile_image, fallback: "no_image.jpg", size:'60x60') %>

  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th>
      <%= link_to following_user_path(user) do %>
        <%= user.following.count %>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th>
      <%= link_to followers_user_path(user) do %>
        <%= user.followers.count %>
      <% end %>
    </th>
  </tr>
</table>

<div class='row'>
  <% unless current_user == user %>
    <%= render "relationships/follow", user: user %>
  <% else %>
    <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
  <% end %>
</div>

app/views/users/_search.html.erb
<h4>検索結果</h4>
<table class='table table-borderd'>
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= search_book %></td>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <div><%= link_to "グループを作成する", new_group_path %> | <%= link_to "グループ一覧", groups_path %></div>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$("#search_result").html("<%= j(render 'search', search_book: @search_book) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>

      <% if @user.id == current_user.id %>
        <%= render 'books/count', data: @data, today_book: @today_book, yesterday_book: @yesterday_book, two_day_book: @two_day_book, three_day_book: @three_day_book, four_day_book: @four_day_book, five_day_book: @five_day_book, six_day_book: @six_day_book %>

        <table class='table'>
          <%= form_with url: user_search_path(@user), method: :get do |f| %>
            <%= f.date_field :created_at %>
            <%= f.submit '検索', class: 'btn btn-primary'  %>
          <% end %>
        </table>

        <div id="search_result">
          <% if @search_book.present? %>
            <%= render 'search', search_book: @search_book %>　#③
          <% end %>
        </div>

      <% end %>

    </div>
  </div>
</div>